// Generated by CoffeeScript 1.6.3
var Emailer, options;

Emailer = require('../lib/emailer');

options = {
  to: {
    email: "chasepettit@gmail.com",
    name: "Chase Pettit"
  },
  subject: "FourVolt Inquiry",
  template: "inquiry"
};

exports.sendMessage = function(req, res) {
  var data, emailer;
  data = req.body;
  emailer = new Emailer(options, data);
  return emailer.send(function(err, result) {
    if (err) {
      return console.log("error sending email: " + err);
    } else {
      return res.send(data);
    }
  });
};
